<%@ Page Title="" Language="C#" MasterPageFile="~/MasterAdmin.Master" AutoEventWireup="true" CodeBehind="Page_Admin5.aspx.cs" Inherits="Academic.PagesAdmin.Page_Admin5" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <style>
    #page5{
            color:#dc3545;
        }
    .RadAutoCompleteBox_Bootstrap .racTokenList {
    border-color: #ccc;
    color: #333;
    background-color: #fff;
    padding: 0;
    border-radius: 4px;
    box-shadow: inset 0 1px 1px rgb(0 0 0 / 8%);
    padding: 0.375rem 0.75rem !important;
    font-weight: 100;
}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        <div class="div-basic d-flex justify-content-center w-100 mt-4">
            <div class="div-emelment2 shedow ">
                <i class="fa-solid fa-book ico"></i><i class="fa-solid fa-user-graduate ico"></i>
                <h4 class="text-dark" style="font-size: 20px; margin-bottom: 20px; display:inline-block ;">مـــــواد
                    الطالــــب
                </h4>
                <asp:Label Visible="false" ID="lblterm" runat="server" Text=""></asp:Label>
                <div class="input-group pb-4">
                    <div class="form-outline">
                        <input type="search" id="form1" placeholder="بحث عن طالب بالاسم" class="form-control" />
                    </div>
                    <button type="button" class="btn btn-secondary" style="margin-right: 1px;">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
                <form runat="server">
                    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
                    <div class="row">
                          <div class="form-outline col-12">
                              
                                <span class="text-secondary">اسم الطالب:</span><asp:Label ID="lblID" runat="server" Text=""></asp:Label>
                              <telerik:RadAutoCompleteBox class="form-control" type="text" placeholder="من فضلك ادخل اسم الطالب"  Width="100%" ID="autosID" runat="server" DataSourceID="StudentName" AutoPostBack="True" DataTextField="Name"></telerik:RadAutoCompleteBox>
                              <asp:SqlDataSource ID="StudentName" runat="server" ConnectionString="<%$ ConnectionStrings:AcademicDBConnectionString %>" SelectCommand="SELECT [NationalID], [Name] FROM [Student]"></asp:SqlDataSource>                          </div>
                        <div class="form-outline mb-4">
                                <span class="text-secondary">اسم المادة:</span>
                            <asp:DropDownList ID="ddlsbject" runat="server" class="form-select" DataSourceID="DataStudent" DataTextField="SubjectName" DataValueField="SubjectID" OnSelectedIndexChanged="ddlsbject_SelectedIndexChanged"></asp:DropDownList>
                                <asp:SqlDataSource ID="DataStudent" runat="server" ConnectionString="<%$ ConnectionStrings:AcademicDBConnectionString %>" SelectCommand="SELECT [SubjectID], [SubjectName] FROM [Subjects] where Ishide=@Ishide">
                                    <SelectParameters>
                                        <asp:Parameter DefaultValue="false" Name="Ishide" />
                                    </SelectParameters>
                                </asp:SqlDataSource>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div data-toggle="collapse" class="pt-1 col-12  text-center">
                            <asp:Button ID="btnAdd" class="btn w-25 btn-danger  btn-lg btn-block"  runat="server" Text="اضـــــافة" OnClick="btnAdd_Click" />
                        </div>
                    </div>
                     <div class="form-outline mt-3  text-center">
                         <asp:Label ID="lblbAdded" runat="server" Text="تمت الاضافة بنجاح" ForeColor="#42BA96" Font-Bold="True" Font-Size="20px" Visible="False"></asp:Label>
                    </div>

                <div class="div-table">
                    <telerik:RadGrid ID="dgv" runat="server" CellSpacing="-1" DataSourceID="DataSbjcrt_student" GridLines="Both" AllowAutomaticDeletes="True" AutoGenerateDeleteColumn="True" AllowSorting="True">
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

                        <MasterTableView DataSourceID="DataSbjcrt_student" AutoGenerateColumns="False" DataKeyNames="SubjectID,stNationalID" AllowSorting="False">
                            <CommandItemSettings ShowExportToWordButton="True" />
                            <Columns>
                                <telerik:GridBoundColumn DataField="SubjectID" HeaderText="كود المادة" SortExpression="SubjectID" UniqueName="SubjectID" FilterControlAltText="Filter SubjectID column" ReadOnly="True"></telerik:GridBoundColumn>
                                <telerik:GridBoundColumn DataField="Name" HeaderText="اسم الطالب" SortExpression="Name" UniqueName="Name" FilterControlAltText="Filter Name column"></telerik:GridBoundColumn>
                                <telerik:GridBoundColumn DataField="Term" HeaderText="الترم" SortExpression="Term" UniqueName="Term" FilterControlAltText="Filter Term column"></telerik:GridBoundColumn>
                                <telerik:GridBoundColumn DataField="AcademicYear" FilterControlAltText="Filter AcademicYear column" HeaderText="السنة الدراسية" SortExpression="AcademicYear" UniqueName="AcademicYear">
                                </telerik:GridBoundColumn>
                            </Columns>
                        </MasterTableView>
                        <HeaderStyle BackColor="LightSlateGray" BorderStyle="Solid" Font-Bold="True" Font-Size="13pt" ForeColor="White" />
                    </telerik:RadGrid>
                    <asp:SqlDataSource runat="server" ID="DataSbjcrt_student" ConnectionString='<%$ ConnectionStrings:AcademicDBConnectionString %>' DeleteCommand="DELETE FROM [Student_Subject] WHERE [stNationalID] = @stNationalID AND [SubjectID] = @SubjectID" InsertCommand="INSERT INTO Student_Subject(stNationalID, SubjectID, Term, LevelID, TypeOkayID) VALUES (@stNationalID, @SubjectID, @Term,@LeveID,@TypeOkayID)" SelectCommand="SELECT dbo.Student_Subject.SubjectID, dbo.Student.Name, dbo.Student_Subject.Term, dbo.Student_Subject.AcademicYear, dbo.Student_Subject.stNationalID
FROM     dbo.Student INNER JOIN
                  dbo.Student_Subject ON dbo.Student.NationalID = dbo.Student_Subject.stNationalID" UpdateCommand="UPDATE [Student_Subject] SET [Term] = @Term WHERE [stNationalID] = @stNationalID AND [SubjectID] = @SubjectID">
                        <DeleteParameters>
                            <asp:Parameter Name="stNationalID" Type="String"></asp:Parameter>
                            <asp:Parameter Name="SubjectID" Type="String"></asp:Parameter>
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:SessionParameter Name="stNationalID" SessionField="x" Type="String" />
                            <asp:ControlParameter ControlID="ddlsbject" Name="SubjectID" PropertyName="SelectedValue" Type="String" />
                            <asp:ControlParameter Name="Term" Type="String" ControlID="lblterm" PropertyName="Text" />
                            <asp:SessionParameter DefaultValue="" Name="LeveID" SessionField="LevelID" />
                            <asp:Parameter DefaultValue="2" Name="TypeOkayID" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="Term" Type="String"></asp:Parameter>
                            <asp:Parameter Name="stNationalID" Type="String"></asp:Parameter>
                            <asp:Parameter Name="SubjectID" Type="String"></asp:Parameter>
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </div>
                
            </div>
        </div>
                </form>


     <script>
         window.onload = function () {
             var element = document.getElementById("show");
             element.classList.add("show");
         };
     </script>
</asp:Content>
