<%@ Page Title="" Language="C#" MasterPageFile="~/MasterAdmin.Master" AutoEventWireup="true" CodeBehind="Page_Admin8.aspx.cs" Inherits="Academic.PagesAdmin.Page_Admin8" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <style>
    #page8{
            color:#dc3545;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div class="div-basic d-flex justify-content-center w-100 mt-4">
            <div class="div-emelment2 shedow ">
                <i class="fa fa-briefcase ico" aria-hidden="true"></i>
                <h4 class="text-dark" style="font-size: 20px; margin-bottom: 20px; display:inline-block ;">
                    ساعات المرشد الاكاديمـــي
                </h4>
                <div class="collapse show" id="dis">
                    <form runat="server">
                        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
                        <div class="form-outline mb-4 col-12">
                                <span class="text-secondary">اسم المرشد:</span>
                            <asp:DropDownList class="form-select" ID="ddlDocID" runat="server" DataSourceID="DataDoctor" DataTextField="AdvName" DataValueField="NationalID">
                            </asp:DropDownList>
                            <asp:SqlDataSource runat="server" ID="DataDoctor" ConnectionString='<%$ ConnectionStrings:AcademicDBConnectionString %>' SelectCommand="SELECT [NationalID], [AdvName] FROM [Advisor]"></asp:SqlDataSource>
                        </div>
                        <div class="row">
                            <div class="form-outline mb-1 col-12 col-md-4">
                                <span class="text-secondary">الايام:</span>
                                <asp:DropDownList class="form-select" ID="DDlData" runat="server">
                                        <asp:ListItem>السبت</asp:ListItem>
                                        <asp:ListItem>الاحد</asp:ListItem>
                                        <asp:ListItem>الاثنين</asp:ListItem>
                                        <asp:ListItem>الثلاثاء</asp:ListItem>
                                        <asp:ListItem>الاربعاء</asp:ListItem>
                                        <asp:ListItem>الخميس</asp:ListItem>
                                    </asp:DropDownList>
                            </div>
                            <div class="form-outline mb-1 col-12 col-md-4">
                                <span class="text-secondary">من:</span>
                               <asp:TextBox ID="txtFrom" runat="server" class="form-control" placeholder="من الساعة" required></asp:TextBox>
                            </div>
                            <div class="form-outline mb-1 col-12 col-md-4">
                                <span class="text-secondary">الى:</span>
                               <asp:TextBox ID="txtto" runat="server" class="form-control" placeholder="الى الساعة" required></asp:TextBox>
                            </div>
                        </div>
                         <div class="row">
                        <div data-toggle="collapse" class="pt-1 col-12  text-center">
                            <asp:Button ID="btnAdd" class="btn w-25 btn-danger  btn-lg btn-block"  runat="server" Text="اضـــــافة" OnClick="btnAdd_Click" />
                        </div>
                    </div>
                     <div class="form-outline mt-3  text-center">
                         <asp:Label ID="lblbAdded" runat="server" Text="تمت الاضافة بنجاح" ForeColor="#42BA96" Font-Bold="True" Font-Size="20px" Visible="False"></asp:Label>
                    </div>
                    
                </div>
                <div class="div-table">
                    <telerik:RadGrid ID="dgv" runat="server" CellSpacing="-1" DataSourceID="DataAddvisor" GridLines="Both" AllowAutomaticDeletes="True" AutoGenerateDeleteColumn="True">
<GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>

                        <MasterTableView DataKeyNames="advNationalID,AdDay" DataSourceID="DataAddvisor" AutoGenerateColumns="False">
                            <Columns>
                                <telerik:GridBoundColumn DataField="AdvName" HeaderText="اسم المرشد" SortExpression="AdvName" UniqueName="AdvName" FilterControlAltText="Filter AdvName column"></telerik:GridBoundColumn>
                                <telerik:GridBoundColumn DataField="AdDay" ReadOnly="True" HeaderText="يوم الحضور" SortExpression="AdDay" UniqueName="AdDay" FilterControlAltText="Filter AdDay column"></telerik:GridBoundColumn>
                                <telerik:GridBoundColumn DataField="fromHour" HeaderText="من الساعة" SortExpression="fromHour" UniqueName="fromHour" DataType="System.Int32" FilterControlAltText="Filter fromHour column"></telerik:GridBoundColumn>
                                <telerik:GridBoundColumn DataField="toHour" HeaderText="الى الساعة" SortExpression="toHour" UniqueName="toHour" DataType="System.Int32" FilterControlAltText="Filter toHour column"></telerik:GridBoundColumn>
                            </Columns>
                        </MasterTableView>
                        <HeaderStyle BackColor="LightSlateGray" BorderStyle="Solid" Font-Bold="True" Font-Size="13pt" ForeColor="White" />
                    </telerik:RadGrid>
                    <asp:SqlDataSource runat="server" ID="DataAddvisor" ConnectionString='<%$ ConnectionStrings:AcademicDBConnectionString %>' DeleteCommand="DELETE FROM [Advisor_Hours] WHERE [advNationalID] = @advNationalID AND [AdDay] = @AdDay" InsertCommand="INSERT INTO [Advisor_Hours] ([advNationalID], [AdDay], [fromHour], [toHour]) VALUES (@advNationalID, @AdDay, @fromHour, @toHour)" SelectCommand="SELECT dbo.Advisor_Hours.*, dbo.Advisor.AdvName
FROM     dbo.Advisor_Hours INNER JOIN
                  dbo.Advisor ON dbo.Advisor_Hours.advNationalID = dbo.Advisor.NationalID" UpdateCommand="UPDATE [Advisor_Hours] SET [fromHour] = @fromHour, [toHour] = @toHour WHERE [advNationalID] = @advNationalID AND [AdDay] = @AdDay">
                        <DeleteParameters>
                            <asp:Parameter Name="advNationalID" Type="Int32"></asp:Parameter>
                            <asp:Parameter Name="AdDay" Type="String"></asp:Parameter>
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:ControlParameter ControlID="ddlDocID" Name="advNationalID" PropertyName="SelectedValue" Type="Int32" />
                            <asp:ControlParameter ControlID="DDlData" Name="AdDay" PropertyName="SelectedValue" Type="String" />
                            <asp:ControlParameter ControlID="txtFrom" Name="fromHour" PropertyName="Text" Type="Int32" />
                            <asp:ControlParameter ControlID="txtto" Name="toHour" PropertyName="Text" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="fromHour" Type="Int32"></asp:Parameter>
                            <asp:Parameter Name="toHour" Type="Int32"></asp:Parameter>
                            <asp:Parameter Name="advNationalID" Type="Int32"></asp:Parameter>
                            <asp:Parameter Name="AdDay" Type="String"></asp:Parameter>
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </div>
                    </form>
            </div>
          <script>
         window.onload = function () {
             var element = document.getElementById("show");
             element.classList.add("show");
         };
          </script>

        </div>
</asp:Content>
