<%@ Page Title="" Language="C#" MasterPageFile="~/MasterAdmin.Master" AutoEventWireup="true" CodeBehind="Page_Admin2.aspx.cs" Inherits="Academic.PagesAdmin.Page_Admin2" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <style>
    #page2{
            color:#dc3545;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div class="div-basic d-flex justify-content-center w-100 mt-4">
            <div class="div-emelment2 shedow ">
                <i class="fa-solid fa-city ico"></i>
                <h4 class="text-dark" style="font-size: 20px; margin-bottom: 20px;display: inline-block;">
                    الاقســـــــــام
                </h4>
                <form runat="server">
                <div class="input-group pb-4">
                    <div class="form-outline">
                        <asp:TextBox ID="txtSearch" runat="server" type="search" placeholder="بحث عن قسم بالكود" class="form-control" OnTextChanged="txtSearch_TextChanged"></asp:TextBox>
                    </div>
                    <lable type="button" class="btn btn-secondary" style="margin-right: 1px;">
                        <i class="fas fa-search"></i>
                    </lable>
                </div>
                    
                    <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                        <ContentTemplate>
                    <div class="row">
                        <div class="form-outline mb-1 col-12">
                             <span class="text-secondary">اسم القسم:</span>
                             <asp:TextBox ID="txtName" runat="server" class="form-control"   placeholder="من فضلك ادخل اسم القسم" required></asp:TextBox>
                        </div>
                        <div class="form-outline mb-1 col-12">
                        <span class="text-secondary">الهاتف:</span>
                        <asp:TextBox ID="txtPhone" runat="server" class="form-control" type="number"  onKeyDown="if(this.value.length==11 && event.keyCode!=8) return false;"  placeholder="من فضلك ادخل رقم الهاتف" required></asp:TextBox>
                    </div>
                    </div>

                    <div class="row">
                        <div data-toggle="collapse" class="pt-1 col-12  text-center">
                            <asp:Button ID="btnAddDep" class="btn w-25 btn-danger  btn-lg btn-block"  runat="server" Text="اضـــــافة" OnClick="btnAddDep_Click" />
                        </div>
                    </div>
                  <div class="form-outline mt-3  text-center">
                         <asp:Label ID="lblbAdded" runat="server" Text="تمت الاضافة بنجاح" ForeColor="#42BA96" Font-Bold="True" Font-Size="20px" Visible="False"></asp:Label>
                         
                    </div>
                <div class="div-table">
                    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
                    <telerik:RadGrid ID="Dgv" runat="server" DataSourceID="SqlDataSource1" AutoGenerateDeleteColumn="True" AutoGenerateEditColumn="True" Font-Bold="True" ForeColor="White" AllowAutomaticDeletes="True" AllowAutomaticInserts="True" AllowAutomaticUpdates="True">
                     <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
                        <MasterTableView AutoGenerateColumns="False" DataKeyNames="DepID" DataSourceID="SqlDataSource1">
                            <Columns>
                                <telerik:GridTemplateColumn DataField="DepID" DataType="System.Int32" FilterControlAltText="Filter DepID column" HeaderText="رقم القسم" SortExpression="DepID" UniqueName="DepID">
                                    
                                    <ItemTemplate>
                                        <asp:Label ID="DepIDLabel" runat="server" Text='<%# Eval("DepID") %>'></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>
                                <telerik:GridTemplateColumn DataField="DepName" FilterControlAltText="Filter DepName column" HeaderText="اسم القسم" SortExpression="DepName" UniqueName="DepName">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="DepNameTextBox" runat="server" Text='<%# Bind("DepName") %>' placeholder="من فضلك ادخل اسم القسم" required></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="DepNameLabel" runat="server" Text='<%# Eval("DepName") %>'></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>
                                <telerik:GridTemplateColumn DataField="Phone" FilterControlAltText="Filter Phone column" HeaderText="الهاتف" SortExpression="Phone" UniqueName="Phone">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="PhoneTextBox" runat="server" Text='<%# Bind("Phone") %>'  placeholder="من فضلك ادخل رقم الهاتف"  type="number"  onKeyDown="if(this.value.length==11 && event.keyCode!=8) return false;" required></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="PhoneLabel" runat="server" Text='<%# Eval("Phone") %>'></asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>
                            </Columns>
                        </MasterTableView>
                        <HeaderStyle BackColor="#6c757d" BorderStyle="Solid" Font-Bold="True" Font-Size="12pt" ForeColor="White" />
                    </telerik:RadGrid>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:AcademicDBConnectionString %>" SelectCommand="SELECT * FROM [Department]" DeleteCommand="DELETE FROM [Department] WHERE [DepID] = @DepID" InsertCommand="INSERT INTO [Department] ([DepName], [Phone]) VALUES (@DepName, @Phone)" UpdateCommand="UPDATE [Department] SET [DepName] = @DepName, [Phone] = @Phone WHERE [DepID] = @DepID">
                        <DeleteParameters>
                            <asp:Parameter Name="DepID" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="DepName" Type="String" />
                            <asp:Parameter Name="Phone" Type="String" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="DepName" Type="String" />
                            <asp:Parameter Name="Phone" Type="String" />
                            <asp:Parameter Name="DepID" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </div>
            </div>
                            </ContentTemplate>
                    </asp:UpdatePanel>
         </form>
            <asp:SqlDataSource ID="SqlDataAdded" runat="server" ConnectionString="<%$ ConnectionStrings:AcademicDBConnectionString %>" DeleteCommand="DELETE FROM [Department] WHERE [DepID] = @DepID" InsertCommand="INSERT INTO [Department] ([DepName], [Phone]) VALUES (@DepName, @Phone)" SelectCommand="SELECT * FROM [Department]" UpdateCommand="UPDATE [Department] SET [DepName] = @DepName, [Phone] = @Phone WHERE [DepID] = @DepID">
                <DeleteParameters>
                    <asp:Parameter Name="DepID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:ControlParameter ControlID="txtName" Name="DepName" PropertyName="Text" Type="String" />
                    <asp:ControlParameter ControlID="txtPhone" Name="Phone" PropertyName="Text" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="DepName" Type="String" />
                    <asp:Parameter Name="Phone" Type="String" />
                    <asp:Parameter Name="DepID" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>

    <script>
         window.onload = function () {
             var element = document.getElementById("show");
             element.classList.add("show");
         };
     </script>
     </div>
</asp:Content>
